### ISSUE TITLE
[Bug] Scorecard test can fail with "failed to get Cryostat CR: resource name may not be empty"

### ISSUE THREAD

**Issue by ebaron** [cryostatio/cryostat-operator#841]
I observed this failure once. Perhaps we can guard against it somehow.

```yaml
{
  "kind": "Test",
  "apiVersion": "scorecard.operatorframework.io/v1alpha3",
  "spec": {
    "image": "quay.io/cryostat/cryostat-operator-scorecard:3.0.0-20240511064726",
    "entrypoint": [
      "cryostat-scorecard-tests",
      "--installOpenShiftCertManager",
      "cryostat-config-change"
    ],
    "labels": {
      "suite": "cryostat",
      "test": "cryostat-config-change"
    },
    "storage": {
      "spec": {
        "mountPath": {}
      }
    }
  },
  "status": {
    "results": [
      {
        "name": "cryostat-config-change",
        "log": "OpenShift version is: 4.14.28
          OperatorHub patched to enable default catalog sources
          Created cert-manager-operator namespace
          Created OperatorGroup for cert-manager-operator
          Created Subscription for openshift-cert-manager-operator in cert-manager-operator
          ClusterServiceVersion cert-manager-operator.v1.13.1 successfully installed
          deployment cryostat-config-change is not yet found
          deployment cryostat-config-change is not yet found
          deployment cryostat-config-change is not yet found
          deployment cryostat-config-change is not yet found
          deployment cryostat-config-change is not yet found
          deployment cryostat-config-change is not yet found
          deployment cryostat-config-change is not yet found
          deployment cryostat-config-change is not yet found
          deployment cryostat-config-change is not yet found
          deployment cryostat-config-change is not yet found
          deployment cryostat-config-change is not yet found
          deployment cryostat-config-change is not yet found
          deployment cryostat-config-change is not yet available
          deployment cryostat-config-change is not yet available
          deployment cryostat-config-change is not yet available
          deployment cryostat-config-change is not yet available
          deployment cryostat-config-change is not yet available
          deployment cryostat-config-change is not yet available
          deployment cryostat-config-change is not yet available
          deployment cryostat-config-change is not yet available
          deployment cryostat-config-change is not yet available
          deployment cryostat-config-change is not yet available
          deployment cryostat-config-change is not yet available
          deployment cryostat-config-change is not yet available
          deployment cryostat-config-change is not yet available
          deployment cryostat-config-change is not yet available
          deployment cryostat-config-change is not yet available
          deployment cryostat-config-change is not yet available
          deployment cryostat-config-change is not yet available
          deployment cryostat-config-change is not yet available
          deployment cryostat-config-change is not yet available
          deployment cryostat-config-change is not yet available
          deployment cryostat-config-change is not yet available
          deployment cryostat-config-change is not yet available
          deployment cryostat-config-change is not yet available
          deployment cryostat-config-change is not yet available
          deployment cryostat-config-change is not yet available
          deployment cryostat-config-change is not yet available
          deployment cryostat-config-change is not yet available
          deployment cryostat-config-change is not yet available
          deployment cryostat-config-change is not yet available
          deployment cryostat-config-change is not yet available
          deployment cryostat-config-change is available
          application has access to the following namespaces: [oo-r2g96]
          application is available at https://cryostat-config-change-oo-r2g96.apps.example.com
          
          WORKLOAD EVENTS:
          deployment cryostat-config-change conditions:
          	Available == True, MinimumReplicasAvailable: Deployment has minimum availability.
          	Progressing == True, NewReplicaSetAvailable: ReplicaSet \"cryostat-config-change-6c5cdd77d5\" has successfully progressed.
          deployment cryostat-config-change warning events:
          replica set cryostat-config-change-6c5cdd77d5 conditions:
          replica set cryostat-config-change-6c5cdd77d5 warning events:
          pod cryostat-config-change-6c5cdd77d5-h6qkh phase: Running
          pod cryostat-config-change-6c5cdd77d5-h6qkh conditions:
          	Initialized == True, : 
          	Ready == True, : 
          	ContainersReady == True, : 
          	PodScheduled == True, : 
          pod cryostat-config-change-6c5cdd77d5-h6qkh warning events:
          	Unhealthy: Readiness probe failed: /var/run/postgresql:5432 - no response
          
          	Unhealthy: Startup probe failed: Get \"http://10.128.2.21:8333/status\": dial tcp 10.128.2.21:8333: connect: connection refused",
        "state": "fail",
        "errors": [
          "Cryostat redeployment did not become available: failed to update Cryostat CR: failed to get Cryostat CR: resource name may not be empty"
        ],
        "creationTimestamp": null
      }
    ]
  }
}
```

**Comment by tthvo** [comment]
> failed to get Cryostat CR: resource name may not be empty

It's quite surprising how the CR struct can happen to lose the `Name`... Do you have any leads on how this could happen?

**Comment by tthvo** [comment]
I think, in my view, somehow the marshaling process of the  CR object (during `POST`) causes the loss of structure field. No idea how internally k8s client work so I don't have concrete evidence.

But, seems like if we could assign the CR back on line `119` below, it should fix the issue?

Create CR:

https://github.com/cryostatio/cryostat-operator/blob/0832d987bb5c614aeff83277de6ef061e17e84d1/internal/test/scorecard/tests.go#L119

Call Update:

https://github.com/cryostatio/cryostat-operator/blob/0832d987bb5c614aeff83277de6ef061e17e84d1/internal/test/scorecard/common_utils.go#L332

k8s API Call:

https://github.com/cryostatio/cryostat-operator/blob/0832d987bb5c614aeff83277de6ef061e17e84d1/internal/test/scorecard/clients.go#L156

**Comment by ebaron** [comment]
> I think, in my view, somehow the marshaling process of the CR object (during `POST`) causes the loss of structure field. No idea how internally k8s client work so I don't have concrete evidence.

It makes me wonder if we're swallowing an error somewhere and that's why the CR is possibly a zero value.

> But, seems like if we could assign the CR back on line `119` below, it should fix the issue?

Probably, but this is still odd.

**Comment by tthvo** [comment]
> It makes me wonder if we're swallowing an error somewhere and that's why the CR is possibly a zero value.

Too odd indeed. I would expect the `cr` variable used in `updateAndWaitTillCryostatAvailable` to come from the initial CR struct, which should have the name.

https://github.com/cryostatio/cryostat-operator/blob/0a426ad312bd1a247753e50abfe40cdfcdb7c28d/internal/test/scorecard/tests.go#L116

Though, would it make sense for the error to have the CR name? For example, `failed to get Cryostat CR my-test-cr: some-error-message`. That would help debugging at least.

**Comment by ebaron** [comment]
> Though, would it make sense for the error message to have the CR name? For example, `failed to get Cryostat CR "my-test-cr": some-error-message`. That would help debugging at least. And we can do the fix for line 119 for now.

It's worth a try. This might be pretty difficult to reproduce, so some extra logging might be the best we can do, unless we notice a problem in the code.

**Comment by ebaron** [comment]
I'm still seeing this in our downstream testing:
```json
            "state": "fail",
            "errors": [
              "Cryostat redeployment did not become available: failed to update Cryostat CR \"\": failed to get Cryostat CR \"\": resource name may not be empty"
            ],
```

I haven't been able to reproduce it normally upstream, but have been able to force it by applying the following change:
```diff
diff --git a/internal/test/scorecard/common_utils.go b/internal/test/scorecard/common_utils.go
index b3c45d4c..509efb3d 100644
--- a/internal/test/scorecard/common_utils.go
+++ b/internal/test/scorecard/common_utils.go
@@ -460,6 +460,16 @@ func (r *TestResources) updateAndWaitTillCryostatAvailable(cr *operatorv1beta2.C
                        return fmt.Errorf("failed to get Cryostat CR \"%s\": %s", cr.Name, err.Error())
                }
 
+               // XXX force conflict error
+               cr2 := cr.DeepCopy()
+               cr2.Annotations = map[string]string{
+                       "foo": "bar",
+               }
+               _, err = r.Client.OperatorCRDs().Cryostats(cr.Namespace).Update(context.Background(), cr2)
+               if err != nil {
+                       return err
+               }
+
                cr.Spec.StorageOptions = &operatorv1beta2.StorageConfiguration{
                        PVC: &operatorv1beta2.PersistentVolumeClaimConfig{
                                Spec: &corev1.PersistentVolumeClaimSpec{

```

Running with `make test-scorecard-local SCORECARD_TEST_SELECTION=cryostat-config-change`, I get the above error. I believe I've discovered the cause and will open a PR to fix it.
